---
 - name: Generate config
   template: src=templates/etc/openvpn/{{ item }}.j2 dest=/etc/openvpn/{{ item }} mode=0700
   with_items:
           - "config.conf"
   tags: 
     - openvpn configFile Send

 - name: restart service openvpn
   service:
     name: openvpn
     state: restarted
   tags:
     - openvpn start
     
 - name: enable service
   service: 
        name: "openvpn@config.conf"
        enabled: yes
   tags:
     - openvpn enable service
