---
- name: Generate config
  template: src={{ item }}.j2 dest={{ openvpn_etcdir }}/{{ item }} mode=0700
  with_items: 
          - "config.conf"
       
- name: Enable service open vpn
    service: name=openvpn state=started enabled=yes
