---
 - name: Generate config
   template: src={{ item }}.j2 dest={{ openvpn_conf_dir }}/{{ item }} mode=0700
   with_items:
           - "config.conf"
   tags: 
     - openvpn config

 - name: restart service openvpn
   service:
     name: openvpn
     state: restarted
   tags:
     - openvpn start
     
 - name: enable service
   service: 
        name: "openvpn@{{openvpn_conf_dir}}/config.conf"
        enabled: yes
   tags:
     - openvpn enable 
