---
- name: Create openvpn_keydir directory
  command:  mkdir "{{ openvpn_etcdir }}"
  args: { creates: "{{ openvpn_etcdir  }}" }

- name: Send sertificates
  template: src={{ item }} dest={{ openvpn_etcdir  }}/{{ item }}
  with_items: [client.key, client.crt, ta.key, ca.crt, base.conf]

- name: Generate scripts
  template: src={{ item }}.j2 dest={{ openvpn_etcdir }}/{{ item }} mode=0700
  with_items: [genconf.sh]

- name: Generate config
  command: "{{ openvpn_etcdir }}/genconf.sh"
  
#- name: Add conf to client
 # template: src=config.conf dest={{ openvpn_etcdir }}/base.conf
  #notify:
#      - openvpn restart

