---
 - name: Generate config
   become_user: {{user}}
   template: src=templates/etc/openvpn/{{ item }}.j2 dest=/etc/openvpn/{{ item }} mode=0700
   with_items:
           - "config.conf"
   tags: 
     - openvpn configFile Send
     
 - name: send sertificates
   copy: src=files/etc/openvpn/{{item}} dest=/etc/openvpn/{{item}} mode=0700
   with_items:
           - "ca.crt"
           - "ta.key"
           - "client1.crt"
           - "client1.key"
   tags: 
     - send sertificates
     
 - name: enable service
   become_user: {{user}}
   service: 
        name: "openvpn@config"
        enabled: "yes"
   tags:
     - openvpn enable service
