---
     - name: Install OpenVpn
       apt:
         name: openvpn
         state: present
         update_cache: yes
       notify:
           - openvpn start
       tags: 
         - openvpn start 
         
     - name: fix xenial systemd service
       template:
         src: openvpn@.service.j2
         dest: /lib/systemd/system/openvpn@.service
         owner: root
         group: root
         mode: 0644
       notify:
           - reload systemd
       tags:
         - openvpn start
