---
     - name: Install OpenVpn
       become_user: {{user}}
       apt:
         name: "openvpn=2.4.*"
         state: "installed"
         update_cache: "yes"
       notify:
           - openvpn@config start
       tags: 
         - openvpn install
       
