---
     - name: Install OpenVpn
       apt:
         name: openvpn
         state: present
         update_cache: yes
       notify:
           - openvpn@config start
       tags: 
         - openvpn install
       
