---
    - name: Add source list
      shell: echo "deb http://build.openvpn.net/debian/openvpn/stable xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
      
    - name: Install OpenVpn 
      apt: pkg=openvpn state=stable
      notify: 
          - openvpn start
