---
    - name: Add source list
      shell: echo "deb http://build.openvpn.net/debian/openvpn/stable xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
      
    - name: Add source list
      shell: apt-get update
      
    - name: Install openvpn 
      apt: pkg=openvpn state=latest
      notify: 
          - openvpn start
