---
 - name: reload systemd
   command: systemctl daemon-reload
   tags:
     - openvpn

 - name: restart openvpn
   service:
     name: openvpn@.service
     state: restarted
   tags:
     - openvpn
